// Everything the page knows that is not behaviour: the API, the colour
// themes, both languages' text, tooltip text and the font choices. Used by
// the .astro components at build time and by the scripts in the browser.

export const API_URL = "https://cv-api.radyalz.ir";
export const STORAGE_KEY = "cv-builder-selection";
export const DEFAULT_THEME = "purple";
export const DEFAULT_VARIANT = "digital";

// Mirrors the theme table in the private cv/helpers/colors.tex. `hex` is the
// theme's main accent; `swatch` only overrides how the dot is drawn here.
export const THEMES = [
  { slug: "purple", label: "Purple", hex: "#7030A0" },
  { slug: "violet", label: "Violet", hex: "#6D28D9" },
  { slug: "indigo", label: "Indigo", hex: "#4338CA" },
  { slug: "blue", label: "Blue", hex: "#1D4ED8" },
  { slug: "sky", label: "Sky", hex: "#0284C7" },
  { slug: "teal", label: "Teal", hex: "#0F766E" },
  { slug: "emerald", label: "Emerald", hex: "#047857" },
  { slug: "green", label: "Green", hex: "#15803D" },
  { slug: "olive", label: "Olive", hex: "#4D7C0F" },
  { slug: "amber", label: "Amber", hex: "#B45309" },
  { slug: "orange", label: "Orange", hex: "#C2410C" },
  { slug: "red", label: "Red", hex: "#B91C1C" },
  { slug: "rose", label: "Rose", hex: "#BE123C" },
  { slug: "burgundy", label: "Burgundy", hex: "#8C1C3D" },
  { slug: "brown", label: "Brown", hex: "#7C4A21" },
  { slug: "slate", label: "Slate", hex: "#334155" },
  { slug: "graphite", label: "Graphite", hex: "#463C64" },
  {
    slug: "mono",
    label: "Black & White",
    hex: "#1A1A1A",
    swatch: "linear-gradient(135deg, #1a1a1a 0 50%, #e9e9e9 50% 100%)",
  },
];

export const THEME_BY_SLUG = new Map(THEMES.map((theme) => [theme.slug, theme]));
export const VARIANTS = new Set([DEFAULT_VARIANT, "print"]);

export const DEFAULT_LANGUAGE = "en";
export const LANGUAGES = new Set([DEFAULT_LANGUAGE, "fa"]);

// Page text in both languages. The accessibility menu switches between
// them; English fills any key Persian is missing.
export const STRINGS = {
  en: {
    eyebrow: "ON-DEMAND CV",
    name: "Radman Alizadeh",
    lead: "Generate the newest version of my CV, in whichever colour and edition you prefer.",
    accent: "Accent",
    edition: "Edition",
    cvLanguage: "CV language",
    digital: "Digital",
    print: "Print",
    generate: "Generate Latest CV",
    generateAgain: "Generate Again",
    tryAgain: "Try Again",
    building: "Building CV…",
    allCopies: "All published copies",
    preview: "Preview",
    previewFrame: "Published CV preview",
    expand: "Expand",
    tapExpand: "Tap to expand",
    leadTablet: "Generate the newest version of my CV: set its colour, edition and language in CV options, then build a fresh copy or download the published one. The preview underneath shows the chosen copy; expand it to read it full screen.",
    leadPhone: "Generate the newest version of my CV: set its colour, edition and language in CV options, then build a fresh copy or download the published one. Tap the preview to read it full screen.",
    installApp: "Install the app",
    installIos: "In Safari, tap the Share button, then Add to Home Screen.",
    saveBackground: "Save the background",
    saveBackgroundNote: "Just the background, at this window's size, as a still image or a video to use as a wallpaper.",
    saveImage: "Image",
    videoLength: "Video length",
    recordVideo: "Record video",
    recordingLeft: "Recording… {n}s left",
    recordingDone: "Saved.",
    noVideo: "This browser can't record video; the image still works.",
    cancel: "Cancel",
    cvOptions: "CV options",
    howItWorks: "How it works",
    tourStart: "Take the tour",
    tourTopics: "Or show me one part:",
    tourNext: "Next",
    tourBack: "Back",
    tourDone: "Done",
    tourClose: "Close the tour",
    tourStep: "{n} of {total}",
    tourOptionsTitle: "CV options",
    tourOptionsText: "Shows the colour, edition and language of the copy. Tap it to change them; the reset icon in its menu puts all three back.",
    tourMainTitle: "The main button",
    tourMainText: "Does what it says: generates a fresh copy of the CV (built from source, which takes about a minute) or downloads the one already published.",
    tourChooseTitle: "Choose the action",
    tourChooseText: "Opens the list of actions: generate, download, or see every published copy. The one you pick becomes the main button.",
    tourPreviewTitle: "The preview",
    tourPreviewPhone: "The top of the chosen copy. Tap it to read the whole CV full screen, with its links working.",
    tourPreviewTablet: "The chosen copy, scrollable, with its links working. Expand opens it full screen, with fit and zoom tools.",
    tourA11yTitle: "Accessibility",
    leadDesktopInfo: "Generate the newest version of my CV: choose its colour, edition and language with the controls below, check the preview beside them, then build a fresh copy or download the published one.",
    tourAccentTitle: "Accent colour",
    tourAccentText: "Colours the name, headings, rules and dates in the CV. Open it to pick a preset, or mix any colour of your own.",
    tourEditionTitle: "Edition",
    tourEditionText: "Digital keeps the clickable links to the portfolio, email and profiles, for reading on screen. Print leaves them out and is laid out for paper.",
    tourLanguageTitle: "CV language",
    tourLanguageText: "English reads left to right with Gregorian dates; Persian reads right to left with Solar Hijri dates and durations.",
    tourResetTitle: "Reset",
    tourResetText: "Puts the colour, edition and language back to purple, digital and English. It wakes up once you change one.",
    tourGenerateTitle: "Generate",
    tourGenerateText: "Builds a fresh copy from source with today's experience durations, which takes about a minute, then downloads it. If the published copy is already current, that one downloads at once.",
    tourDownloadTitle: "Download",
    tourDownloadText: "Saves the copy already published for this choice, with no waiting.",
    tourAllTitle: "All published copies",
    tourAllText: "Opens the GitHub release with every colour, edition and language built so far.",
    tourOptionsInside: "Tap it and its menu opens with three controls. Next, each of them.",
    tourActionsTitle: "The list of actions",
    tourActionsText: "The arrow beside the main button opens this list. Whatever you pick becomes the main button, and it stays picked for this visit. Next, how they differ.",
    tourLinksTitle: "Clickable links",
    tourLinksText: "The links in the CV work right here in the preview: email, phone, portfolio and profiles, each opening in a new tab. This shows how many there are; tap it to light them all up for a moment.",
    tourExpandTitle: "Expand",
    tourExpandText: "Grows the preview to fill the window, with fit width, fit page and zoom at the bottom, and Download and Close beside them.",
    tourPageLangTitle: "Page language",
    tourPageLangText: "Switches this page between English and Persian, right to left included. The CV's own language is chosen separately, in its own control.",
    tourAppearanceTitle: "Appearance",
    tourAppearanceText: "Dark or light. The page follows your device's setting until you pick one here.",
    tourTextSizeTitle: "Text size",
    tourTextSizeText: "Four sizes for all of the page's text, easing smoothly from one to the next. Each A shows its own size.",
    tourFontTitle: "Font",
    tourFontText: "Typefaces for the page, with a different set for English and for Persian. The CV itself keeps its own fonts.",
    tourAdmireButtonTitle: "Admire the background",
    tourAdmireButtonText: "Hides the card so the skull artwork behind it has the whole screen. Next, a look at it.",
    tourAdmireTitle: "Admiring the background",
    tourAdmireText: "This is the background on its own. To bring the card back, press this eye button, which only appears while admiring, or Escape. The card comes back when the tour moves on.",
    tourAccessibilityText: "Opens the accessibility menu. Next, each of its settings.",
    tourReadTitle: "Reading full screen",
    tourReadText: "The copy fills the window now. This pill names it and says when it was published; the PDF scrolls, and its links work.",
    tourReadNarrow: "The copy fills the screen now. This pill names it; tap it to see when it was published and how many links it has. The PDF scrolls, and its links work.",
    tourBarLinksText: "Lights up every link in the CV for a moment, so you can see what can be clicked.",
    tourFitWidthText: "Makes the page as wide as the window, edge to edge. The easiest way to read it.",
    tourFitPageText: "Shows a whole page at once, to see how it is laid out.",
    tourFitSelectText: "Opens fit width and fit page, stacked above it. Its icon shows the one in use.",
    tourZoomText: "Zooms out and in a step at a time. The percentage is the size against the printed page.",
    tourZoomTabletText: "Zooms out and in a step at a time; fit width or fit page brings it back.",
    tourZoomPhoneText: "The monocle opens zoom in and zoom out, stacked above it. It stays open, so you can tap several times.",
    tourBarDownloadText: "Saves the copy you are reading.",
    tourCloseText: "Shrinks the preview back into the card. Escape, or a click beside it, does the same.",
    tourPreviewDesktop: "The chosen copy, scrollable, with its links working. Expand grows it to fill the window, with fit and zoom tools.",
    tourA11yText: "Page language, light or dark, text size and fonts. Its Admire button hides the card so you can enjoy the background.",
    moreActions: "More actions",
    actionGenerateNote: "Build a fresh copy now",
    actionDownloadNote: "Save the published copy",
    actionAllNote: "Every copy, on GitHub",
    previewFailed: "Couldn't load the preview.",
    listingFailed: "Couldn't reach the CV service.",
    retry: "Retry",
    justGenerated: "Generated just now",
    touchHint: "Press and hold any button to see what it does.",
    admire: "Admire the background",
    showCard: "Show the card",
    close: "Close",
    chooseAccent: "Choose an accent colour",
    presets: "Preset colours",
    custom: "Custom",
    customHex: "Custom colour, hex value",
    use: "Use",
    typical: "Typical build: under a minute",
    readyTitle: "Latest CV is ready",
    readyText: "Your download should start automatically.",
    failedTitle: "Build failed",
    a11y: "Accessibility",
    pageLanguage: "Page language",
    appearance: "Appearance",
    dark: "Dark",
    light: "Light",
    textSize: "Text size",
    sizeSmall: "Small",
    sizeDefault: "Default",
    sizeLarge: "Large",
    sizeLarger: "Larger",
    lang_en: "English",
    lang_fa: "Persian",
    published: "Published {date}",
    notGenerated: "This combination has not been generated yet. Use Generate Latest CV to build it, and the result appears here.",
    elapsed: "Elapsed: {time}",
    requestingTitle: "Requesting a fresh build…",
    requestingText: "Connecting to the CV build service. {selection}.",
    startedTitle: "Build started",
    startedText: "Build #{id} is running. You can keep this tab open.",
    renderingTitle: "Rendering the latest CV…",
    renderingText: "Compiling the document and recalculating current experience durations.",
    queuedTitle: "Build queued…",
    queuedText: "The request was accepted and is waiting for a runner.",
    completeTitle: "Build complete",
    publishedStarting: "The newest CV has been published. Starting your download…",
    upToDate: "This copy is already up to date. Starting your download…",
    errStart: "Unable to start CV generation.",
    errNoId: "The build service did not return a build ID.",
    errStatus: "Unable to check CV generation status.",
    errNoUrl: "The build completed without a download URL.",
    errFailed: "The CV build failed.",
    errGeneric: "CV generation failed. Please try again.",
    hexInvalid: "Enter a colour as six hex digits, for example #FF8800.",
    hintLight: "Very light colours can be hard to read on a printed CV. The headings are darkened automatically, but a mid-tone colour usually reads better.",
    hintCustom: "The lighter and muted shades of the CV are derived from this colour automatically.",
    download: "Download published copy",
    downloadShort: "Download",
    pdfTools: "Page size",
    fitWidth: "Fit width",
    fitPage: "Fit page",
    copyDetails: "Copy details",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoom: "Zoom",
    font: "Font",
    reset: "Reset",
    system: "System",
    resetPrefs: "Reset to defaults",
    linksHint: "{n} clickable links",
    linksHintOne: "1 clickable link",
  },
  fa: {
    eyebrow: "رزومه به‌روز",
    name: "رادمان علیزاده",
    lead: "جدیدترین نسخه رزومه‌ام را با رنگ و نسخه دلخواه‌تان بسازید.",
    accent: "رنگ",
    edition: "نسخه",
    cvLanguage: "زبان رزومه",
    digital: "دیجیتال",
    print: "چاپی",
    generate: "ساخت جدیدترین رزومه",
    generateAgain: "ساخت دوباره",
    tryAgain: "تلاش دوباره",
    building: "در حال ساخت رزومه…",
    allCopies: "همه نسخه‌های منتشرشده",
    preview: "پیش‌نمایش",
    previewFrame: "پیش‌نمایش رزومه منتشرشده",
    expand: "بزرگ‌نمایی",
    tapExpand: "برای بزرگ‌نمایی بزنید",
    leadTablet: "جدیدترین نسخه رزومه‌ام را بسازید: رنگ، نسخه و زبانش را در «گزینه‌های رزومه» انتخاب کنید و سپس نسخه‌ای تازه بسازید یا نسخه منتشرشده را دانلود کنید. پیش‌نمایش پایین همان نسخه را نشان می‌دهد؛ برای دیدن تمام‌صفحه آن را بزرگ کنید.",
    leadPhone: "جدیدترین نسخه رزومه‌ام را بسازید: رنگ، نسخه و زبانش را در «گزینه‌های رزومه» انتخاب کنید و سپس نسخه‌ای تازه بسازید یا نسخه منتشرشده را دانلود کنید. برای دیدن تمام‌صفحه روی پیش‌نمایش بزنید.",
    installApp: "نصب برنامه",
    installIos: "در سافاری، دکمه اشتراک‌گذاری و سپس «افزودن به صفحه اصلی» را بزنید.",
    saveBackground: "ذخیره پس‌زمینه",
    saveBackgroundNote: "فقط پس‌زمینه، به اندازه همین پنجره، به‌صورت عکس یا ویدیو برای والپیپر.",
    saveImage: "عکس",
    videoLength: "طول ویدیو",
    recordVideo: "ضبط ویدیو",
    recordingLeft: "در حال ضبط… {n} ثانیه مانده",
    recordingDone: "ذخیره شد.",
    noVideo: "این مرورگر نمی‌تواند ویدیو ضبط کند؛ عکس همچنان کار می‌کند.",
    cancel: "لغو",
    cvOptions: "گزینه‌های رزومه",
    howItWorks: "روش کار",
    tourStart: "شروع راهنما",
    tourTopics: "یا فقط یک بخش را نشانم بده:",
    tourNext: "بعدی",
    tourBack: "قبلی",
    tourDone: "تمام",
    tourClose: "بستن راهنما",
    tourStep: "{n} از {total}",
    tourOptionsTitle: "گزینه‌های رزومه",
    tourOptionsText: "رنگ، نسخه و زبان نسخه را نشان می‌دهد. برای تغییرشان رویش بزنید؛ نماد بازنشانی در منوی آن هر سه را به حالت پیش‌فرض برمی‌گرداند.",
    tourMainTitle: "دکمه اصلی",
    tourMainText: "همان کاری را می‌کند که رویش نوشته: نسخه‌ای تازه از رزومه می‌سازد (از منبع، حدود یک دقیقه) یا نسخه منتشرشده را دانلود می‌کند.",
    tourChooseTitle: "انتخاب کار",
    tourChooseText: "فهرست کارها را باز می‌کند: ساخت، دانلود یا دیدن همه نسخه‌های منتشرشده. هر کدام را انتخاب کنید، دکمه اصلی می‌شود.",
    tourPreviewTitle: "پیش‌نمایش",
    tourPreviewPhone: "بالای نسخه انتخاب‌شده. برای خواندن کل رزومه به‌صورت تمام‌صفحه، با پیوندهای فعال، رویش بزنید.",
    tourPreviewTablet: "نسخه انتخاب‌شده، قابل پیمایش و با پیوندهای فعال. «بزرگ‌نمایی» آن را تمام‌صفحه با ابزار اندازه و زوم باز می‌کند.",
    tourA11yTitle: "دسترس‌پذیری",
    leadDesktopInfo: "جدیدترین نسخه رزومه‌ام را بسازید: رنگ، نسخه و زبانش را با گزینه‌های پایین انتخاب کنید، پیش‌نمایش کنارشان را ببینید و سپس نسخه‌ای تازه بسازید یا نسخه منتشرشده را دانلود کنید.",
    tourAccentTitle: "رنگ رزومه",
    tourAccentText: "رنگ نام، عنوان‌ها، خط‌ها و تاریخ‌های رزومه. بازش کنید تا یکی از رنگ‌های آماده یا هر رنگ دلخواهی را انتخاب کنید.",
    tourEditionTitle: "نسخه",
    tourEditionText: "دیجیتال پیوندهای نمونه‌کار، ایمیل و پروفایل‌ها را برای خواندن روی صفحه نگه می‌دارد. چاپی آن‌ها را ندارد و برای کاغذ چیده شده است.",
    tourLanguageTitle: "زبان رزومه",
    tourLanguageText: "انگلیسی چپ‌به‌راست با تاریخ میلادی است؛ فارسی راست‌به‌چپ با تاریخ و مدت‌های شمسی.",
    tourResetTitle: "بازنشانی",
    tourResetText: "رنگ، نسخه و زبان را به بنفش، دیجیتال و انگلیسی برمی‌گرداند. پس از تغییر یکی از آن‌ها فعال می‌شود.",
    tourGenerateTitle: "ساخت",
    tourGenerateText: "نسخه‌ای تازه با مدت سوابق تا امروز از منبع می‌سازد، که حدود یک دقیقه طول می‌کشد، و دانلودش می‌کند. اگر نسخه منتشرشده به‌روز باشد، همان فوراً دانلود می‌شود.",
    tourDownloadTitle: "دانلود",
    tourDownloadText: "نسخه‌ای را که برای همین انتخاب منتشر شده، بی‌درنگ ذخیره می‌کند.",
    tourAllTitle: "همه نسخه‌های منتشرشده",
    tourAllText: "صفحه انتشار گیت‌هاب را با همه رنگ‌ها، نسخه‌ها و زبان‌های ساخته‌شده باز می‌کند.",
    tourOptionsInside: "رویش بزنید تا منوی آن با سه گزینه باز شود. در ادامه، هر کدام.",
    tourActionsTitle: "فهرست کارها",
    tourActionsText: "فلش کنار دکمه اصلی این فهرست را باز می‌کند. هر کدام را انتخاب کنید دکمه اصلی می‌شود و در این بازدید همان می‌ماند. در ادامه، تفاوت‌هایشان.",
    tourLinksTitle: "پیوندهای قابل کلیک",
    tourLinksText: "پیوندهای رزومه همین‌جا در پیش‌نمایش کار می‌کنند: ایمیل، تلفن، نمونه‌کار و پروفایل‌ها، هر کدام در زبانه‌ای تازه. این تعدادشان را نشان می‌دهد؛ رویش بزنید تا لحظه‌ای همه روشن شوند.",
    tourExpandTitle: "بزرگ‌نمایی",
    tourExpandText: "پیش‌نمایش را به اندازه پنجره بزرگ می‌کند، با هم‌عرض پنجره، کل صفحه و زوم در پایین، و دانلود و بستن کنارشان.",
    tourPageLangTitle: "زبان صفحه",
    tourPageLangText: "این صفحه را بین انگلیسی و فارسی (با چیدمان راست‌به‌چپ) جابه‌جا می‌کند. زبان خود رزومه جداگانه، با گزینه خودش انتخاب می‌شود.",
    tourAppearanceTitle: "ظاهر",
    tourAppearanceText: "تیره یا روشن. تا وقتی اینجا انتخاب نکنید، صفحه از تنظیم دستگاه شما پیروی می‌کند.",
    tourTextSizeTitle: "اندازه متن",
    tourTextSizeText: "چهار اندازه برای همه متن‌های صفحه، با گذر نرم از یکی به دیگری. هر A اندازه خودش را نشان می‌دهد.",
    tourFontTitle: "قلم",
    tourFontText: "قلم‌های صفحه، با مجموعه‌ای جدا برای انگلیسی و برای فارسی. خود رزومه قلم‌های خودش را نگه می‌دارد.",
    tourAdmireButtonTitle: "تماشای پس‌زمینه",
    tourAdmireButtonText: "کارت را پنهان می‌کند تا طرح جمجمه‌های پشت آن کل صفحه را داشته باشد. در ادامه، نگاهی به آن.",
    tourAdmireTitle: "تماشای پس‌زمینه",
    tourAdmireText: "این پس‌زمینه به‌تنهایی است. برای بازگرداندن کارت، این دکمه چشم را (که فقط هنگام تماشا دیده می‌شود) یا Esc را بزنید. با رفتن راهنما به مرحله بعد، کارت برمی‌گردد.",
    tourAccessibilityText: "منوی دسترس‌پذیری را باز می‌کند. در ادامه، هر یک از تنظیماتش.",
    tourReadTitle: "خواندن تمام‌صفحه",
    tourReadText: "حالا نسخه کل پنجره را گرفته است. این برچسب نامش و تاریخ انتشارش را می‌گوید؛ PDF پیمایش می‌شود و پیوندهایش کار می‌کنند.",
    tourReadNarrow: "حالا نسخه کل صفحه را گرفته است. این برچسب نامش را می‌گوید؛ رویش بزنید تا تاریخ انتشار و تعداد پیوندها را ببینید. PDF پیمایش می‌شود و پیوندهایش کار می‌کنند.",
    tourBarLinksText: "همه پیوندهای رزومه را لحظه‌ای روشن می‌کند تا ببینید چه چیزهایی قابل کلیک است.",
    tourFitWidthText: "صفحه را هم‌عرض پنجره، از لبه تا لبه، نشان می‌دهد. راحت‌ترین حالت برای خواندن.",
    tourFitPageText: "یک صفحه کامل را یک‌جا نشان می‌دهد تا چیدمانش را ببینید.",
    tourFitSelectText: "هم‌عرض پنجره و کل صفحه را، روی هم بالای خودش، باز می‌کند. نمادش حالت فعلی را نشان می‌دهد.",
    tourZoomText: "گام‌به‌گام کوچک و بزرگ می‌کند. درصد، اندازه نسبت به صفحه چاپی است.",
    tourZoomTabletText: "گام‌به‌گام کوچک و بزرگ می‌کند؛ هم‌عرض پنجره یا کل صفحه آن را برمی‌گرداند.",
    tourZoomPhoneText: "عینک، بزرگ‌نمایی و کوچک‌نمایی را روی هم بالای خودش باز می‌کند. باز می‌ماند تا چند بار بزنید.",
    tourBarDownloadText: "نسخه‌ای را که می‌خوانید ذخیره می‌کند.",
    tourCloseText: "پیش‌نمایش را به کارت برمی‌گرداند. Esc یا کلیک کنار آن هم همین کار را می‌کند.",
    tourPreviewDesktop: "نسخه انتخاب‌شده، قابل پیمایش و با پیوندهای فعال. «بزرگ‌نمایی» آن را به اندازه پنجره با ابزار اندازه و زوم باز می‌کند.",
    tourA11yText: "زبان صفحه، روشن یا تیره، اندازه متن و قلم‌ها. دکمه «تماشای پس‌زمینه» در آن کارت را پنهان می‌کند تا پس‌زمینه را ببینید.",
    moreActions: "کارهای دیگر",
    actionGenerateNote: "همین حالا نسخه‌ای تازه بساز",
    actionDownloadNote: "ذخیره نسخه منتشرشده",
    actionAllNote: "همه نسخه‌ها، در گیت‌هاب",
    previewFailed: "بارگذاری پیش‌نمایش ممکن نشد.",
    listingFailed: "دسترسی به سرویس رزومه ممکن نشد.",
    retry: "تلاش دوباره",
    justGenerated: "همین حالا ساخته شد",
    touchHint: "برای دیدن کار هر دکمه، آن را لمس کنید و نگه دارید.",
    admire: "تماشای پس‌زمینه",
    showCard: "نمایش کارت",
    close: "بستن",
    chooseAccent: "انتخاب رنگ",
    presets: "رنگ‌های آماده",
    custom: "دلخواه",
    customHex: "رنگ دلخواه، کد هگز",
    use: "اعمال",
    typical: "زمان معمول ساخت: کمتر از یک دقیقه",
    readyTitle: "رزومه آماده است",
    readyText: "دانلود باید خودکار آغاز شود.",
    failedTitle: "ساخت ناموفق بود",
    a11y: "دسترس‌پذیری",
    pageLanguage: "زبان صفحه",
    appearance: "ظاهر",
    dark: "تیره",
    light: "روشن",
    textSize: "اندازه متن",
    sizeSmall: "کوچک",
    sizeDefault: "پیش‌فرض",
    sizeLarge: "بزرگ",
    sizeLarger: "بزرگ‌تر",
    lang_en: "انگلیسی",
    lang_fa: "فارسی",
    published: "منتشرشده در {date}",
    notGenerated: "این ترکیب هنوز ساخته نشده است. با «ساخت جدیدترین رزومه» آن را بسازید تا نتیجه همین‌جا نمایش داده شود.",
    elapsed: "زمان سپری‌شده: {time}",
    requestingTitle: "درخواست ساخت تازه…",
    requestingText: "در حال اتصال به سرویس ساخت رزومه. {selection}.",
    startedTitle: "ساخت آغاز شد",
    startedText: "ساخت شماره {id} در حال اجراست. می‌توانید این صفحه را باز نگه دارید.",
    renderingTitle: "در حال ساخت جدیدترین رزومه…",
    renderingText: "در حال کامپایل سند و محاسبه دوباره مدت سوابق کاری.",
    queuedTitle: "در صف ساخت…",
    queuedText: "درخواست پذیرفته شد و منتظر اجراست.",
    completeTitle: "ساخت کامل شد",
    publishedStarting: "جدیدترین رزومه منتشر شد. دانلود آغاز می‌شود…",
    upToDate: "این نسخه به‌روز است. دانلود آغاز می‌شود…",
    errStart: "آغاز ساخت رزومه ممکن نشد.",
    errNoId: "سرویس ساخت شناسه‌ای برنگرداند.",
    errStatus: "بررسی وضعیت ساخت ممکن نشد.",
    errNoUrl: "ساخت کامل شد اما پیوند دانلودی برنگشت.",
    errFailed: "ساخت رزومه ناموفق بود.",
    errGeneric: "ساخت رزومه ناموفق بود. دوباره تلاش کنید.",
    hexInvalid: "رنگ را به‌صورت شش رقم هگز وارد کنید، مثلاً #FF8800.",
    hintLight: "رنگ‌های خیلی روشن در رزومه چاپی سخت خوانده می‌شوند. عنوان‌ها خودکار تیره‌تر می‌شوند، اما رنگی با روشنایی متوسط معمولاً خواناتر است.",
    hintCustom: "سایه‌های روشن‌تر و ملایم رزومه خودکار از همین رنگ ساخته می‌شوند.",
    download: "دانلود نسخه منتشرشده",
    downloadShort: "دانلود",
    pdfTools: "اندازه صفحه",
    fitWidth: "هم‌عرض پنجره",
    fitPage: "کل صفحه",
    copyDetails: "جزئیات نسخه",
    zoomIn: "بزرگ‌نمایی",
    zoomOut: "کوچک‌نمایی",
    zoom: "بزرگ‌نمایی و کوچک‌نمایی",
    font: "قلم",
    reset: "بازنشانی",
    system: "سیستم",
    resetPrefs: "بازگشت به پیش‌فرض",
    linksHint: "{n} پیوند قابل کلیک",
    linksHintOne: "۱ پیوند قابل کلیک",
  },
};

// Tooltip text: a title and a line on what the control does for each
// data-tip key. tipContent() adds the live details (file, colour, date…).
export const TIPS = {
  en: {
    installApp: ["Install the app", "Adds it to your home screen or desktop with its own icon. It opens full screen and at once, even offline."],
    saveBackground: ["Save the background", "Download the background alone as an image, or record 15 to 30 seconds of it as a video wallpaper, at this window's size."],
    cvOptions: ["CV options", "Choose the colour, edition and language of the copy."],
    generate: ["Generate a fresh copy", "Compiles the CV from source with today's experience durations, then downloads it. If the published copy is already current, that one downloads at once."],
    download: ["Download the published copy", "Downloads the copy already built for this selection, with no waiting."],
    downloadMissing: ["Not published yet", "Nothing has been built for this combination. Use Generate Latest CV and it becomes available here."],
    downloadCustom: ["No published copy", "Custom colours are built on request and never kept: Generate Latest CV makes one and hands it straight to you."],
    allCopies: ["All published copies", "Opens the GitHub release that holds every colour, edition and language built so far."],
    accent: ["Accent colour", "Colours the name, headings, rules and dates in the CV. Choose a preset or any colour of your own."],
    digital: ["Digital edition", "Keeps the clickable links to the portfolio, email and profiles. Best for reading on screen or sending on."],
    print: ["Print edition", "Leaves out the portfolio links and is laid out for paper."],
    cvEn: ["English CV", "Left to right, with Gregorian dates."],
    cvFa: ["Persian CV", "Right to left, with Solar Hijri dates and durations."],
    expand: ["Expand the preview", "Grows the card to fill the window so the CV can be read at full size."],
    close: ["Close the preview", "Shrinks the card back to the builder."],
    pick: ["Pick any colour", "Opens the colour picker. The lighter and muted shades of the CV are derived from it automatically."],
    use: ["Apply this colour", "Uses the hex value typed in the box as the accent."],
    a11y: ["Accessibility", "Page language, appearance, text size and fonts. Remembered on this device."],
    uiEn: ["English page", "Shows this page in English. The CV's own language is set under CV language."],
    uiFa: ["Persian page", "Shows this page in Persian, right to left. The CV's own language is set under CV language."],
    dark: ["Dark appearance", "Light text on a dark page."],
    light: ["Light appearance", "Dark text on a bright page."],
    sizeSmall: ["Small text", "Scales every piece of text on this page."],
    sizeDefault: ["Default text size", "Scales every piece of text on this page."],
    sizeLarge: ["Large text", "Scales every piece of text on this page."],
    sizeLarger: ["Larger text", "Scales every piece of text on this page."],
    swatch: ["{name}", "Sets this preset as the CV's accent colour."],
    fitWidth: ["Fit width", "Pages fill the width; scroll to read on."],
    fitPage: ["Fit page", "A whole page at once."],
    zoomIn: ["Zoom in", "Enlarges the pages."],
    zoomOut: ["Zoom out", "Shrinks the pages."],
    zoom: ["Zoom", "Opens zoom out and zoom in."],
    moreActions: ["Choose the action", "Pick what the button beside it does: generate a fresh copy, download the published one, or open all copies."],
    admire: ["Admire the background", "Hides the card so the skulls have the screen to themselves. Press again (or Escape) to bring it back."],
    retry: ["Try again", "Fetches the preview again. Check your connection if it keeps failing."],
    resetCv: ["Reset CV options", "Puts the colour, edition and CV language back to their defaults."],
    resetPrefs: ["Reset page settings", "Puts the page language, appearance, text size and fonts back to their defaults. Appearance follows your system again."],
    linksHint: ["Clickable links", "The contact details, websites and portfolio entries in this copy open when clicked, here and in the downloaded PDF. Click to highlight them."],
  },
  fa: {
    installApp: ["نصب برنامه", "آن را با نماد خودش به صفحه اصلی یا دسکتاپ اضافه می‌کند. تمام‌صفحه و فوری باز می‌شود، حتی بدون اینترنت."],
    saveBackground: ["ذخیره پس‌زمینه", "فقط پس‌زمینه را به‌صورت عکس دانلود کنید، یا ۱۵ تا ۳۰ ثانیه از آن را برای والپیپر ویدیویی ضبط کنید، به اندازه همین پنجره."],
    cvOptions: ["گزینه‌های رزومه", "رنگ، نسخه و زبان نسخه را انتخاب کنید."],
    generate: ["ساخت نسخه تازه", "رزومه را با مدت سوابق تا امروز از نو می‌سازد و دانلود می‌کند. اگر نسخه منتشرشده به‌روز باشد، همان فوراً دانلود می‌شود."],
    download: ["دانلود نسخه منتشرشده", "نسخه‌ای را که برای همین انتخاب ساخته شده، بی‌درنگ دانلود می‌کند."],
    downloadMissing: ["هنوز منتشر نشده", "برای این ترکیب نسخه‌ای ساخته نشده است. با «ساخت جدیدترین رزومه» بسازید تا این‌جا در دسترس باشد."],
    downloadCustom: ["نسخه منتشرشده‌ای نیست", "رنگ‌های دلخواه فقط هنگام درخواست ساخته و هرگز نگه‌داری نمی‌شوند: «ساخت جدیدترین رزومه» یکی می‌سازد و مستقیم به شما می‌دهد."],
    allCopies: ["همه نسخه‌های منتشرشده", "صفحه انتشار گیت‌هاب را باز می‌کند که همه رنگ‌ها، نسخه‌ها و زبان‌های ساخته‌شده را دارد."],
    accent: ["رنگ رزومه", "رنگ نام، عنوان‌ها، خط‌ها و تاریخ‌های رزومه. یکی از رنگ‌های آماده یا هر رنگ دلخواه."],
    digital: ["نسخه دیجیتال", "پیوندهای نمونه‌کار، ایمیل و پروفایل‌ها را نگه می‌دارد. مناسب خواندن روی صفحه و ارسال."],
    print: ["نسخه چاپی", "بدون پیوندهای نمونه‌کار و چیده‌شده برای کاغذ."],
    cvEn: ["رزومه انگلیسی", "چپ‌به‌راست، با تاریخ میلادی."],
    cvFa: ["رزومه فارسی", "راست‌به‌چپ، با تاریخ و مدت‌های شمسی."],
    expand: ["بزرگ‌نمایی پیش‌نمایش", "کارت را به اندازه پنجره بزرگ می‌کند تا رزومه در اندازه کامل خوانده شود."],
    close: ["بستن پیش‌نمایش", "کارت را به سازنده برمی‌گرداند."],
    pick: ["انتخاب هر رنگی", "انتخابگر رنگ را باز می‌کند. سایه‌های روشن‌تر و ملایم رزومه خودکار از آن ساخته می‌شوند."],
    use: ["اعمال این رنگ", "کد هگز واردشده را رنگ رزومه می‌کند."],
    a11y: ["دسترس‌پذیری", "زبان صفحه، ظاهر، اندازه متن و قلم‌ها. روی همین دستگاه به خاطر سپرده می‌شود."],
    uiEn: ["صفحه انگلیسی", "این صفحه را به انگلیسی نشان می‌دهد. زبان خود رزومه در «زبان رزومه» انتخاب می‌شود."],
    uiFa: ["صفحه فارسی", "این صفحه را به فارسی و راست‌به‌چپ نشان می‌دهد. زبان خود رزومه در «زبان رزومه» انتخاب می‌شود."],
    dark: ["ظاهر تیره", "متن روشن روی زمینه تیره."],
    light: ["ظاهر روشن", "متن تیره روی زمینه روشن."],
    sizeSmall: ["متن کوچک", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeDefault: ["اندازه پیش‌فرض", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeLarge: ["متن بزرگ", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeLarger: ["متن بزرگ‌تر", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    swatch: ["{name}", "این رنگ آماده را رنگ رزومه می‌کند."],
    fitWidth: ["هم‌عرض پنجره", "صفحه‌ها کل عرض را پر می‌کنند؛ برای ادامه اسکرول کنید."],
    fitPage: ["کل صفحه", "یک صفحه کامل در یک نگاه."],
    zoomIn: ["بزرگ‌نمایی", "صفحه‌ها را بزرگ‌تر می‌کند."],
    zoomOut: ["کوچک‌نمایی", "صفحه‌ها را کوچک‌تر می‌کند."],
    zoom: ["بزرگ‌نمایی", "کوچک‌نمایی و بزرگ‌نمایی را باز می‌کند."],
    moreActions: ["انتخاب کار", "انتخاب کنید دکمه کنارش چه کند: ساخت نسخه تازه، دانلود نسخه منتشرشده یا باز کردن همه نسخه‌ها."],
    admire: ["تماشای پس‌زمینه", "کارت را پنهان می‌کند تا فقط جمجمه‌ها دیده شوند. برای بازگرداندن دوباره بزنید (یا Esc)."],
    retry: ["تلاش دوباره", "پیش‌نمایش را دوباره دریافت می‌کند. اگر باز هم ناموفق بود، اتصال خود را بررسی کنید."],
    resetCv: ["بازنشانی گزینه‌های رزومه", "رنگ، نسخه و زبان رزومه را به پیش‌فرض برمی‌گرداند."],
    resetPrefs: ["بازنشانی تنظیمات صفحه", "زبان صفحه، ظاهر، اندازه متن و قلم‌ها را به پیش‌فرض برمی‌گرداند. ظاهر دوباره از تنظیم سیستم پیروی می‌کند."],
    linksHint: ["پیوندهای قابل کلیک", "اطلاعات تماس، وب‌سایت‌ها و نمونه‌کارهای این نسخه با کلیک باز می‌شوند، هم این‌جا و هم در PDF دانلودشده. برای دیدنشان کلیک کنید."],
  },
};

// Labels for the detail rows under a tooltip.
export const FACTS = {
  en: {
    file: "File", colour: "Colour", edition: "Edition", language: "Language",
    published: "Published", size: "Size", status: "Status", shortcut: "Shortcut",
    copies: "Copies", latest: "Latest", opens: "Opens", newTab: "In a new tab",
    notYet: "Not built yet", buildTime: "Build time", buildTimeValue: "About half a minute",
    scale: "Scale", style: "Style", page: "Page", fonts: "Font",
    appearance: "Appearance", text: "Text size", hex: "Hex", builtCopies: "Built copies",
  },
  fa: {
    file: "فایل", colour: "رنگ", edition: "نسخه", language: "زبان",
    published: "انتشار", size: "حجم", status: "وضعیت", shortcut: "میان‌بر",
    copies: "نسخه‌ها", latest: "آخرین", opens: "باز شدن", newTab: "در زبانه تازه",
    notYet: "هنوز ساخته نشده", buildTime: "زمان ساخت", buildTimeValue: "حدود نیم دقیقه",
    scale: "مقیاس", style: "سبک", page: "صفحه", fonts: "قلم",
    appearance: "ظاهر", text: "اندازه متن", hex: "هگز", builtCopies: "نسخه‌های ساخته‌شده",
  },
};

// Page fonts offered in the accessibility menu: [English, Persian] text.
export const EN_FONTS = {
  inter: { name: "Inter", note: ["Neutral and very legible; the original look of this page.", "خنثی و بسیار خوانا؛ ظاهر اصلی این صفحه."], style: ["Grotesque sans", "بی‌میانه گروتسک"] },
  manrope: { name: "Manrope", note: ["Geometric, with softer and rounder curves.", "هندسی، با انحناهای نرم‌تر و گردتر."], style: ["Geometric sans", "بی‌میانه هندسی"] },
  jakarta: { name: "Plus Jakarta Sans", note: ["Modern and slightly condensed, with a friendly tone.", "مدرن و کمی فشرده، با حسی دوستانه."], style: ["Geometric sans", "بی‌میانه هندسی"] },
  plex: { name: "IBM Plex Sans", note: ["Engineered and a little technical.", "مهندسی‌شده و کمی فنی."], style: ["Neo-grotesque", "نئوگروتسک"] },
  grotesk: { name: "Space Grotesk", note: ["A quirky display grotesque with character.", "گروتسکی نمایشی و پرشخصیت."], style: ["Display grotesque", "گروتسک نمایشی"] },
};

export const FA_FONTS = {
  yekan: { name: ["Yekan Bakh", "یکان بخ"], note: ["A clean, modern Persian sans; the default.", "بی‌میانه‌ای مدرن و تمیز؛ پیش‌فرض."], style: ["Sans", "بی‌میانه"] },
  vazir: { name: ["Vazirmatn", "وزیرمتن"], note: ["Open and very readable Persian sans.", "بی‌میانه‌ای باز و بسیار خوانا."], style: ["Sans", "بی‌میانه"] },
  doran: { name: ["Doran", "دوران"], note: ["A rounded, friendly Persian sans with open forms.", "بی‌میانه‌ای گرد و صمیمی با فرم‌های باز."], style: ["Sans", "بی‌میانه"] },
  niloofar: { name: ["XB Niloofar", "نیلوفر"], note: ["A classic naskh with book-like contrast.", "نسخی کلاسیک با کنتراست کتابی."], style: ["Naskh", "نسخ"] },
};

export const FA_COLOURS = {
  purple: "بنفش",
  violet: "بنفشه‌ای",
  indigo: "نیلی",
  blue: "آبی",
  sky: "آبی آسمانی",
  teal: "سبزآبی",
  emerald: "زمردی",
  green: "سبز",
  olive: "زیتونی",
  amber: "کهربایی",
  orange: "نارنجی",
  red: "قرمز",
  rose: "گلبهی",
  burgundy: "زرشکی",
  brown: "قهوه‌ای",
  slate: "سنگی",
  graphite: "گرافیتی",
  mono: "سیاه و سفید",
};

export const UI_KEY = "cv-builder-a11y";
export const TEXT_SIZES = [0.9, 1, 1.15, 1.3];
