// Everything the page knows that is not behaviour: the API, the colour
// themes, both languages' text, tooltip text and the font choices. Used by
// the .astro components at build time and by the scripts in the browser.

export const API_URL = "https://cv-api.radyalz.ir";
export const STORAGE_KEY = "cv-builder-selection";
export const DEFAULT_THEME = "purple";
export const DEFAULT_VARIANT = "digital";

// Mirrors the theme table in the private cv/helpers/colors.tex. `hex` is the
// theme's main accent; `swatch` only overrides how the dot is drawn here.
export const THEMES = [
  { slug: "purple", label: "Purple", hex: "#7030A0" },
  { slug: "violet", label: "Violet", hex: "#6D28D9" },
  { slug: "indigo", label: "Indigo", hex: "#4338CA" },
  { slug: "blue", label: "Blue", hex: "#1D4ED8" },
  { slug: "sky", label: "Sky", hex: "#0284C7" },
  { slug: "teal", label: "Teal", hex: "#0F766E" },
  { slug: "emerald", label: "Emerald", hex: "#047857" },
  { slug: "green", label: "Green", hex: "#15803D" },
  { slug: "olive", label: "Olive", hex: "#4D7C0F" },
  { slug: "amber", label: "Amber", hex: "#B45309" },
  { slug: "orange", label: "Orange", hex: "#C2410C" },
  { slug: "red", label: "Red", hex: "#B91C1C" },
  { slug: "rose", label: "Rose", hex: "#BE123C" },
  { slug: "burgundy", label: "Burgundy", hex: "#8C1C3D" },
  { slug: "brown", label: "Brown", hex: "#7C4A21" },
  { slug: "slate", label: "Slate", hex: "#334155" },
  { slug: "graphite", label: "Graphite", hex: "#463C64" },
  {
    slug: "mono",
    label: "Black & White",
    hex: "#1A1A1A",
    swatch: "linear-gradient(135deg, #1a1a1a 0 50%, #e9e9e9 50% 100%)",
  },
];

export const THEME_BY_SLUG = new Map(THEMES.map((theme) => [theme.slug, theme]));
export const VARIANTS = new Set([DEFAULT_VARIANT, "print"]);

export const DEFAULT_LANGUAGE = "en";
export const LANGUAGES = new Set([DEFAULT_LANGUAGE, "fa"]);

// Page text in both languages. The accessibility menu switches between
// them; English fills any key Persian is missing.
export const STRINGS = {
  en: {
    eyebrow: "ON-DEMAND CV",
    name: "Radman Alizadeh",
    lead: "Generate the newest version of my CV, in whichever colour and edition you prefer.",
    accent: "Accent",
    edition: "Edition",
    cvLanguage: "CV language",
    digital: "Digital",
    print: "Print",
    generate: "Generate Latest CV",
    generateAgain: "Generate Again",
    tryAgain: "Try Again",
    building: "Building CV…",
    allCopies: "All published copies",
    preview: "Preview",
    previewFrame: "Published CV preview",
    expand: "Expand",
    tapExpand: "Tap to expand",
    moreActions: "More actions",
    actionGenerateNote: "Build a fresh copy now",
    actionDownloadNote: "Save the published copy",
    actionAllNote: "Every copy, on GitHub",
    previewFailed: "Couldn't load the preview.",
    listingFailed: "Couldn't reach the CV service.",
    retry: "Retry",
    justGenerated: "Generated just now",
    touchHint: "Press and hold any button to see what it does.",
    admire: "Admire the background",
    showCard: "Show the card",
    close: "Close",
    chooseAccent: "Choose an accent colour",
    presets: "Preset colours",
    custom: "Custom",
    customHex: "Custom colour, hex value",
    use: "Use",
    typical: "Typical build: under a minute",
    readyTitle: "Latest CV is ready",
    readyText: "Your download should start automatically.",
    failedTitle: "Build failed",
    a11y: "Accessibility",
    pageLanguage: "Page language",
    appearance: "Appearance",
    dark: "Dark",
    light: "Light",
    textSize: "Text size",
    sizeSmall: "Small",
    sizeDefault: "Default",
    sizeLarge: "Large",
    sizeLarger: "Larger",
    lang_en: "English",
    lang_fa: "Persian",
    published: "Published {date}",
    notGenerated: "This combination has not been generated yet. Use Generate Latest CV to build it, and the result appears here.",
    elapsed: "Elapsed: {time}",
    requestingTitle: "Requesting a fresh build…",
    requestingText: "Connecting to the CV build service. {selection}.",
    startedTitle: "Build started",
    startedText: "Build #{id} is running. You can keep this tab open.",
    renderingTitle: "Rendering the latest CV…",
    renderingText: "Compiling the document and recalculating current experience durations.",
    queuedTitle: "Build queued…",
    queuedText: "The request was accepted and is waiting for a runner.",
    completeTitle: "Build complete",
    publishedStarting: "The newest CV has been published. Starting your download…",
    upToDate: "This copy is already up to date. Starting your download…",
    errStart: "Unable to start CV generation.",
    errNoId: "The build service did not return a build ID.",
    errStatus: "Unable to check CV generation status.",
    errNoUrl: "The build completed without a download URL.",
    errFailed: "The CV build failed.",
    errGeneric: "CV generation failed. Please try again.",
    hexInvalid: "Enter a colour as six hex digits, for example #FF8800.",
    hintLight: "Very light colours can be hard to read on a printed CV. The headings are darkened automatically, but a mid-tone colour usually reads better.",
    hintCustom: "The lighter and muted shades of the CV are derived from this colour automatically.",
    download: "Download published copy",
    downloadShort: "Download",
    pdfTools: "Page size",
    fitWidth: "Fit width",
    fitPage: "Fit page",
    copyDetails: "Copy details",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    font: "Font",
    reset: "Reset",
    system: "System",
    resetPrefs: "Reset to defaults",
    linksHint: "{n} clickable links",
    linksHintOne: "1 clickable link",
  },
  fa: {
    eyebrow: "رزومه به‌روز",
    name: "رادمان علیزاده",
    lead: "جدیدترین نسخه رزومه‌ام را با رنگ و نسخه دلخواه‌تان بسازید.",
    accent: "رنگ",
    edition: "نسخه",
    cvLanguage: "زبان رزومه",
    digital: "دیجیتال",
    print: "چاپی",
    generate: "ساخت جدیدترین رزومه",
    generateAgain: "ساخت دوباره",
    tryAgain: "تلاش دوباره",
    building: "در حال ساخت رزومه…",
    allCopies: "همه نسخه‌های منتشرشده",
    preview: "پیش‌نمایش",
    previewFrame: "پیش‌نمایش رزومه منتشرشده",
    expand: "بزرگ‌نمایی",
    tapExpand: "برای بزرگ‌نمایی بزنید",
    moreActions: "کارهای دیگر",
    actionGenerateNote: "همین حالا نسخه‌ای تازه بساز",
    actionDownloadNote: "ذخیره نسخه منتشرشده",
    actionAllNote: "همه نسخه‌ها، در گیت‌هاب",
    previewFailed: "بارگذاری پیش‌نمایش ممکن نشد.",
    listingFailed: "دسترسی به سرویس رزومه ممکن نشد.",
    retry: "تلاش دوباره",
    justGenerated: "همین حالا ساخته شد",
    touchHint: "برای دیدن کار هر دکمه، آن را لمس کنید و نگه دارید.",
    admire: "تماشای پس‌زمینه",
    showCard: "نمایش کارت",
    close: "بستن",
    chooseAccent: "انتخاب رنگ",
    presets: "رنگ‌های آماده",
    custom: "دلخواه",
    customHex: "رنگ دلخواه، کد هگز",
    use: "اعمال",
    typical: "زمان معمول ساخت: کمتر از یک دقیقه",
    readyTitle: "رزومه آماده است",
    readyText: "دانلود باید خودکار آغاز شود.",
    failedTitle: "ساخت ناموفق بود",
    a11y: "دسترس‌پذیری",
    pageLanguage: "زبان صفحه",
    appearance: "ظاهر",
    dark: "تیره",
    light: "روشن",
    textSize: "اندازه متن",
    sizeSmall: "کوچک",
    sizeDefault: "پیش‌فرض",
    sizeLarge: "بزرگ",
    sizeLarger: "بزرگ‌تر",
    lang_en: "انگلیسی",
    lang_fa: "فارسی",
    published: "منتشرشده در {date}",
    notGenerated: "این ترکیب هنوز ساخته نشده است. با «ساخت جدیدترین رزومه» آن را بسازید تا نتیجه همین‌جا نمایش داده شود.",
    elapsed: "زمان سپری‌شده: {time}",
    requestingTitle: "درخواست ساخت تازه…",
    requestingText: "در حال اتصال به سرویس ساخت رزومه. {selection}.",
    startedTitle: "ساخت آغاز شد",
    startedText: "ساخت شماره {id} در حال اجراست. می‌توانید این صفحه را باز نگه دارید.",
    renderingTitle: "در حال ساخت جدیدترین رزومه…",
    renderingText: "در حال کامپایل سند و محاسبه دوباره مدت سوابق کاری.",
    queuedTitle: "در صف ساخت…",
    queuedText: "درخواست پذیرفته شد و منتظر اجراست.",
    completeTitle: "ساخت کامل شد",
    publishedStarting: "جدیدترین رزومه منتشر شد. دانلود آغاز می‌شود…",
    upToDate: "این نسخه به‌روز است. دانلود آغاز می‌شود…",
    errStart: "آغاز ساخت رزومه ممکن نشد.",
    errNoId: "سرویس ساخت شناسه‌ای برنگرداند.",
    errStatus: "بررسی وضعیت ساخت ممکن نشد.",
    errNoUrl: "ساخت کامل شد اما پیوند دانلودی برنگشت.",
    errFailed: "ساخت رزومه ناموفق بود.",
    errGeneric: "ساخت رزومه ناموفق بود. دوباره تلاش کنید.",
    hexInvalid: "رنگ را به‌صورت شش رقم هگز وارد کنید، مثلاً #FF8800.",
    hintLight: "رنگ‌های خیلی روشن در رزومه چاپی سخت خوانده می‌شوند. عنوان‌ها خودکار تیره‌تر می‌شوند، اما رنگی با روشنایی متوسط معمولاً خواناتر است.",
    hintCustom: "سایه‌های روشن‌تر و ملایم رزومه خودکار از همین رنگ ساخته می‌شوند.",
    download: "دانلود نسخه منتشرشده",
    downloadShort: "دانلود",
    pdfTools: "اندازه صفحه",
    fitWidth: "هم‌عرض پنجره",
    fitPage: "کل صفحه",
    copyDetails: "جزئیات نسخه",
    zoomIn: "بزرگ‌نمایی",
    zoomOut: "کوچک‌نمایی",
    font: "قلم",
    reset: "بازنشانی",
    system: "سیستم",
    resetPrefs: "بازگشت به پیش‌فرض",
    linksHint: "{n} پیوند قابل کلیک",
    linksHintOne: "۱ پیوند قابل کلیک",
  },
};

// Tooltip text: a title and a line on what the control does for each
// data-tip key. tipContent() adds the live details (file, colour, date…).
export const TIPS = {
  en: {
    generate: ["Generate a fresh copy", "Compiles the CV from source with today's experience durations, then downloads it. If the published copy is already current, that one downloads at once."],
    download: ["Download the published copy", "Downloads the copy already built for this selection, with no waiting."],
    downloadMissing: ["Not published yet", "Nothing has been built for this combination. Use Generate Latest CV and it becomes available here."],
    downloadCustom: ["No published copy", "Custom colours are built on request and never kept: Generate Latest CV makes one and hands it straight to you."],
    allCopies: ["All published copies", "Opens the GitHub release that holds every colour, edition and language built so far."],
    accent: ["Accent colour", "Colours the name, headings, rules and dates in the CV. Choose a preset or any colour of your own."],
    digital: ["Digital edition", "Keeps the clickable links to the portfolio, email and profiles. Best for reading on screen or sending on."],
    print: ["Print edition", "Leaves out the portfolio links and is laid out for paper."],
    cvEn: ["English CV", "Left to right, with Gregorian dates."],
    cvFa: ["Persian CV", "Right to left, with Solar Hijri dates and durations."],
    expand: ["Expand the preview", "Grows the card to fill the window so the CV can be read at full size."],
    close: ["Close the preview", "Shrinks the card back to the builder."],
    pick: ["Pick any colour", "Opens the colour picker. The lighter and muted shades of the CV are derived from it automatically."],
    use: ["Apply this colour", "Uses the hex value typed in the box as the accent."],
    a11y: ["Accessibility", "Page language, appearance, text size and fonts. Remembered on this device."],
    uiEn: ["English page", "Shows this page in English. The CV's own language is set under CV language."],
    uiFa: ["Persian page", "Shows this page in Persian, right to left. The CV's own language is set under CV language."],
    dark: ["Dark appearance", "Light text on a dark page."],
    light: ["Light appearance", "Dark text on a bright page."],
    sizeSmall: ["Small text", "Scales every piece of text on this page."],
    sizeDefault: ["Default text size", "Scales every piece of text on this page."],
    sizeLarge: ["Large text", "Scales every piece of text on this page."],
    sizeLarger: ["Larger text", "Scales every piece of text on this page."],
    swatch: ["{name}", "Sets this preset as the CV's accent colour."],
    fitWidth: ["Fit width", "Pages fill the width; scroll to read on."],
    fitPage: ["Fit page", "A whole page at once."],
    zoomIn: ["Zoom in", "Enlarges the pages."],
    zoomOut: ["Zoom out", "Shrinks the pages."],
    moreActions: ["Choose the action", "Pick what the button beside it does: generate a fresh copy, download the published one, or open all copies."],
    admire: ["Admire the background", "Hides the card so the skulls have the screen to themselves. Press again (or Escape) to bring it back."],
    retry: ["Try again", "Fetches the preview again. Check your connection if it keeps failing."],
    resetCv: ["Reset CV options", "Puts the colour, edition and CV language back to their defaults."],
    resetPrefs: ["Reset page settings", "Puts the page language, appearance, text size and fonts back to their defaults. Appearance follows your system again."],
    linksHint: ["Clickable links", "The contact details, websites and portfolio entries in this copy open when clicked, here and in the downloaded PDF. Click to highlight them."],
  },
  fa: {
    generate: ["ساخت نسخه تازه", "رزومه را با مدت سوابق تا امروز از نو می‌سازد و دانلود می‌کند. اگر نسخه منتشرشده به‌روز باشد، همان فوراً دانلود می‌شود."],
    download: ["دانلود نسخه منتشرشده", "نسخه‌ای را که برای همین انتخاب ساخته شده، بی‌درنگ دانلود می‌کند."],
    downloadMissing: ["هنوز منتشر نشده", "برای این ترکیب نسخه‌ای ساخته نشده است. با «ساخت جدیدترین رزومه» بسازید تا این‌جا در دسترس باشد."],
    downloadCustom: ["نسخه منتشرشده‌ای نیست", "رنگ‌های دلخواه فقط هنگام درخواست ساخته و هرگز نگه‌داری نمی‌شوند: «ساخت جدیدترین رزومه» یکی می‌سازد و مستقیم به شما می‌دهد."],
    allCopies: ["همه نسخه‌های منتشرشده", "صفحه انتشار گیت‌هاب را باز می‌کند که همه رنگ‌ها، نسخه‌ها و زبان‌های ساخته‌شده را دارد."],
    accent: ["رنگ رزومه", "رنگ نام، عنوان‌ها، خط‌ها و تاریخ‌های رزومه. یکی از رنگ‌های آماده یا هر رنگ دلخواه."],
    digital: ["نسخه دیجیتال", "پیوندهای نمونه‌کار، ایمیل و پروفایل‌ها را نگه می‌دارد. مناسب خواندن روی صفحه و ارسال."],
    print: ["نسخه چاپی", "بدون پیوندهای نمونه‌کار و چیده‌شده برای کاغذ."],
    cvEn: ["رزومه انگلیسی", "چپ‌به‌راست، با تاریخ میلادی."],
    cvFa: ["رزومه فارسی", "راست‌به‌چپ، با تاریخ و مدت‌های شمسی."],
    expand: ["بزرگ‌نمایی پیش‌نمایش", "کارت را به اندازه پنجره بزرگ می‌کند تا رزومه در اندازه کامل خوانده شود."],
    close: ["بستن پیش‌نمایش", "کارت را به سازنده برمی‌گرداند."],
    pick: ["انتخاب هر رنگی", "انتخابگر رنگ را باز می‌کند. سایه‌های روشن‌تر و ملایم رزومه خودکار از آن ساخته می‌شوند."],
    use: ["اعمال این رنگ", "کد هگز واردشده را رنگ رزومه می‌کند."],
    a11y: ["دسترس‌پذیری", "زبان صفحه، ظاهر، اندازه متن و قلم‌ها. روی همین دستگاه به خاطر سپرده می‌شود."],
    uiEn: ["صفحه انگلیسی", "این صفحه را به انگلیسی نشان می‌دهد. زبان خود رزومه در «زبان رزومه» انتخاب می‌شود."],
    uiFa: ["صفحه فارسی", "این صفحه را به فارسی و راست‌به‌چپ نشان می‌دهد. زبان خود رزومه در «زبان رزومه» انتخاب می‌شود."],
    dark: ["ظاهر تیره", "متن روشن روی زمینه تیره."],
    light: ["ظاهر روشن", "متن تیره روی زمینه روشن."],
    sizeSmall: ["متن کوچک", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeDefault: ["اندازه پیش‌فرض", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeLarge: ["متن بزرگ", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    sizeLarger: ["متن بزرگ‌تر", "همه متن‌های این صفحه را مقیاس می‌دهد."],
    swatch: ["{name}", "این رنگ آماده را رنگ رزومه می‌کند."],
    fitWidth: ["هم‌عرض پنجره", "صفحه‌ها کل عرض را پر می‌کنند؛ برای ادامه اسکرول کنید."],
    fitPage: ["کل صفحه", "یک صفحه کامل در یک نگاه."],
    zoomIn: ["بزرگ‌نمایی", "صفحه‌ها را بزرگ‌تر می‌کند."],
    zoomOut: ["کوچک‌نمایی", "صفحه‌ها را کوچک‌تر می‌کند."],
    moreActions: ["انتخاب کار", "انتخاب کنید دکمه کنارش چه کند: ساخت نسخه تازه، دانلود نسخه منتشرشده یا باز کردن همه نسخه‌ها."],
    admire: ["تماشای پس‌زمینه", "کارت را پنهان می‌کند تا فقط جمجمه‌ها دیده شوند. برای بازگرداندن دوباره بزنید (یا Esc)."],
    retry: ["تلاش دوباره", "پیش‌نمایش را دوباره دریافت می‌کند. اگر باز هم ناموفق بود، اتصال خود را بررسی کنید."],
    resetCv: ["بازنشانی گزینه‌های رزومه", "رنگ، نسخه و زبان رزومه را به پیش‌فرض برمی‌گرداند."],
    resetPrefs: ["بازنشانی تنظیمات صفحه", "زبان صفحه، ظاهر، اندازه متن و قلم‌ها را به پیش‌فرض برمی‌گرداند. ظاهر دوباره از تنظیم سیستم پیروی می‌کند."],
    linksHint: ["پیوندهای قابل کلیک", "اطلاعات تماس، وب‌سایت‌ها و نمونه‌کارهای این نسخه با کلیک باز می‌شوند، هم این‌جا و هم در PDF دانلودشده. برای دیدنشان کلیک کنید."],
  },
};

// Labels for the detail rows under a tooltip.
export const FACTS = {
  en: {
    file: "File", colour: "Colour", edition: "Edition", language: "Language",
    published: "Published", size: "Size", status: "Status", shortcut: "Shortcut",
    copies: "Copies", latest: "Latest", opens: "Opens", newTab: "In a new tab",
    notYet: "Not built yet", buildTime: "Build time", buildTimeValue: "About half a minute",
    scale: "Scale", style: "Style", page: "Page", fonts: "Font",
    appearance: "Appearance", text: "Text size", hex: "Hex", builtCopies: "Built copies",
  },
  fa: {
    file: "فایل", colour: "رنگ", edition: "نسخه", language: "زبان",
    published: "انتشار", size: "حجم", status: "وضعیت", shortcut: "میان‌بر",
    copies: "نسخه‌ها", latest: "آخرین", opens: "باز شدن", newTab: "در زبانه تازه",
    notYet: "هنوز ساخته نشده", buildTime: "زمان ساخت", buildTimeValue: "حدود نیم دقیقه",
    scale: "مقیاس", style: "سبک", page: "صفحه", fonts: "قلم",
    appearance: "ظاهر", text: "اندازه متن", hex: "هگز", builtCopies: "نسخه‌های ساخته‌شده",
  },
};

// Page fonts offered in the accessibility menu: [English, Persian] text.
export const EN_FONTS = {
  inter: { name: "Inter", note: ["Neutral and very legible; the original look of this page.", "خنثی و بسیار خوانا؛ ظاهر اصلی این صفحه."], style: ["Grotesque sans", "بی‌میانه گروتسک"] },
  manrope: { name: "Manrope", note: ["Geometric, with softer and rounder curves.", "هندسی، با انحناهای نرم‌تر و گردتر."], style: ["Geometric sans", "بی‌میانه هندسی"] },
  jakarta: { name: "Plus Jakarta Sans", note: ["Modern and slightly condensed, with a friendly tone.", "مدرن و کمی فشرده، با حسی دوستانه."], style: ["Geometric sans", "بی‌میانه هندسی"] },
  plex: { name: "IBM Plex Sans", note: ["Engineered and a little technical.", "مهندسی‌شده و کمی فنی."], style: ["Neo-grotesque", "نئوگروتسک"] },
  grotesk: { name: "Space Grotesk", note: ["A quirky display grotesque with character.", "گروتسکی نمایشی و پرشخصیت."], style: ["Display grotesque", "گروتسک نمایشی"] },
};

export const FA_FONTS = {
  yekan: { name: ["Yekan Bakh", "یکان بخ"], note: ["A clean, modern Persian sans; the default.", "بی‌میانه‌ای مدرن و تمیز؛ پیش‌فرض."], style: ["Sans", "بی‌میانه"] },
  vazir: { name: ["Vazirmatn", "وزیرمتن"], note: ["Open and very readable Persian sans.", "بی‌میانه‌ای باز و بسیار خوانا."], style: ["Sans", "بی‌میانه"] },
  doran: { name: ["Doran", "دوران"], note: ["A rounded, friendly Persian sans with open forms.", "بی‌میانه‌ای گرد و صمیمی با فرم‌های باز."], style: ["Sans", "بی‌میانه"] },
  niloofar: { name: ["XB Niloofar", "نیلوفر"], note: ["A classic naskh with book-like contrast.", "نسخی کلاسیک با کنتراست کتابی."], style: ["Naskh", "نسخ"] },
};

export const FA_COLOURS = {
  purple: "بنفش",
  violet: "بنفشه‌ای",
  indigo: "نیلی",
  blue: "آبی",
  sky: "آبی آسمانی",
  teal: "سبزآبی",
  emerald: "زمردی",
  green: "سبز",
  olive: "زیتونی",
  amber: "کهربایی",
  orange: "نارنجی",
  red: "قرمز",
  rose: "گلبهی",
  burgundy: "زرشکی",
  brown: "قهوه‌ای",
  slate: "سنگی",
  graphite: "گرافیتی",
  mono: "سیاه و سفید",
};

export const UI_KEY = "cv-builder-a11y";
export const TEXT_SIZES = [0.9, 1, 1.15, 1.3];
