const byId = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
const one = <T extends HTMLElement = HTMLElement>(selector: string) => document.querySelector(selector) as T;

export const el = {
  generate: byId<HTMLButtonElement>("generateButton"),
  buildPanel: byId("buildPanel"),
  successPanel: byId("successPanel"),
  errorPanel: byId("errorPanel"),
  statusTitle: byId("statusTitle"),
  statusText: byId("statusText"),
  errorText: byId("errorText"),
  elapsedTime: byId("elapsedTime"),
  colourTrigger: byId<HTMLButtonElement>("colourTrigger"),
  colourTriggerLabel: byId("colourTriggerLabel"),
  colourMenu: byId("colourMenu"),
  themeGrid: byId("themeGrid"),
  themeHint: byId("themeHint"),
  customColor: byId<HTMLInputElement>("customColor"),
  customHex: byId<HTMLInputElement>("customHex"),
  customApply: byId<HTMLButtonElement>("customApply"),
  variantToggle: byId("variantToggle"),
  languageToggle: byId("languageToggle"),
  previewPane: one(".card-preview"),
  previewDoc: byId("previewDoc"),
  pdfZoom: byId("pdfZoom"),
  resetButtons: [byId<HTMLButtonElement>("resetCv"), byId<HTMLButtonElement>("resetCvTop")],
  previewError: byId("previewError"),
  previewRetry: byId("previewRetry"),
  linksHints: [...document.querySelectorAll<HTMLElement>(".links-hint")],
  previewState: byId("previewState"),
  previewLabel: byId("previewLabel"),
  previewMeta: byId("previewMeta"),
  previewExpand: byId("previewExpand"),
  previewSkeleton: byId("previewSkeleton"),
  previewBox: one(".preview-frame"),
  previewCollapse: byId("previewCollapse"),
  card: one(".builder-card"),
  expandedLabel: byId("expandedLabel"),
  expandedMeta: byId("expandedMeta"),
  expandedTop: one(".expanded-top"),
  infoToggle: byId("infoToggle"),
  fitPicker: one(".fit-select"),
  fitSelect: byId("fitSelect"),
  zoomPicker: one(".zoom-select"),
  zoomSelect: byId("zoomSelect"),
  expandedDownload: byId<HTMLButtonElement>("expandedDownload"),
  downloadLatest: byId<HTMLButtonElement>("downloadLatest"),
  previewFoot: one(".preview-foot"),
  peekHint: one(".peek-hint"),
};
